/**
 * Cards API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.example.zizi.lab3.model.network;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * Card
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-21T09:21:44.571+02:00")
public class Card   {
  @SerializedName("id")
  private Double id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("mana")
  private BigDecimal mana = null;

  @SerializedName("attack")
  private BigDecimal attack = null;

  @SerializedName("defense")
  private BigDecimal defense = null;

  public Card id(Double id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique identifier")
  public Double getId() {
    return id;
  }

  public void setId(Double id) {
    this.id = id;
  }

  public Card name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Unique identifier
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Unique identifier")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Card mana(BigDecimal mana) {
    this.mana = mana;
    return this;
  }

   /**
   * Unique identifier
   * @return mana
  **/
  @ApiModelProperty(example = "null", value = "Unique identifier")
  public BigDecimal getMana() {
    return mana;
  }

  public void setMana(BigDecimal mana) {
    this.mana = mana;
  }

  public Card attack(BigDecimal attack) {
    this.attack = attack;
    return this;
  }

   /**
   * Unique identifier
   * @return attack
  **/
  @ApiModelProperty(example = "null", value = "Unique identifier")
  public BigDecimal getAttack() {
    return attack;
  }

  public void setAttack(BigDecimal attack) {
    this.attack = attack;
  }

  public Card defense(BigDecimal defense) {
    this.defense = defense;
    return this;
  }

   /**
   * Unique identifier
   * @return defense
  **/
  @ApiModelProperty(example = "null", value = "Unique identifier")
  public BigDecimal getDefense() {
    return defense;
  }

  public void setDefense(BigDecimal defense) {
    this.defense = defense;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Card card = (Card) o;
    return Objects.equals(this.id, card.id) &&
        Objects.equals(this.name, card.name) &&
        Objects.equals(this.mana, card.mana) &&
        Objects.equals(this.attack, card.attack) &&
        Objects.equals(this.defense, card.defense);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, mana, attack, defense);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Card {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mana: ").append(toIndentedString(mana)).append("\n");
    sb.append("    attack: ").append(toIndentedString(attack)).append("\n");
    sb.append("    defense: ").append(toIndentedString(defense)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

